//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument range is too short for given increment..
        /// </summary>
        internal static string Error_ArgumentRangeIsTooShort {
            get {
                return ResourceManager.GetString("Error_ArgumentRangeIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension of the first matrix is invalid..
        /// </summary>
        internal static string Error_FirstMatrixDimensionIsInvalid {
            get {
                return ResourceManager.GetString("Error_FirstMatrixDimensionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function range is invalid..
        /// </summary>
        internal static string Error_FunctionValueRange {
            get {
                return ResourceManager.GetString("Error_FunctionValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument range is invalid..
        /// </summary>
        internal static string Error_InvalidArgumentRange {
            get {
                return ResourceManager.GetString("Error_InvalidArgumentRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrixes cannot be multiplied due to dimensions mismatch..
        /// </summary>
        internal static string Error_MatrixesCannotBeMultipliedDueToDimensions {
            get {
                return ResourceManager.GetString("Error_MatrixesCannotBeMultipliedDueToDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify correct maximum value of matrix element..
        /// </summary>
        internal static string Error_MaxElementValueIsInvalid {
            get {
                return ResourceManager.GetString("Error_MaxElementValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify correct number of files..
        /// </summary>
        internal static string Error_NumberOfFilesIsInvalid {
            get {
                return ResourceManager.GetString("Error_NumberOfFilesIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify output folder..
        /// </summary>
        internal static string Error_OutputFolderIsMissing {
            get {
                return ResourceManager.GetString("Error_OutputFolderIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension of the second matrix is invalid..
        /// </summary>
        internal static string Error_SecondMatrixDimensionIsInvalid {
            get {
                return ResourceManager.GetString("Error_SecondMatrixDimensionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Text_ErrorMessageBox {
            get {
                return ResourceManager.GetString("Text_ErrorMessageBox", resourceCulture);
            }
        }
    }
}
